### ISSUE TITLE
使用ができない

### ISSUE THREAD

**Issue by Shirotan18** [chimaha/dAnimePlus#2]
スクリプトを適用していても、どの機能も使用ができなくなってしまっています。
解像度の表示やスクロールでの音量変更もできなくなっているため、アップデートしていただけると嬉しいです。。。

**Comment by Shirotan18** [comment]
失礼いたしました。スクリプト自体は動作したものの、動画再生が正常にできなかったため、
コード内 178行目のopenUrl の値を、「https:」から「http:」へ変更したところ、問題なく使用できるようになりました。
    const openUrl = "http://animestore.docomo.ne.jp/animestore/sc_d_pc?partId=" + partId;
また、それに伴い、ヘッダの”@match” を追加し、動作させることができました。
    // @match       http://animestore.docomo.ne.jp/animestore/*

**Comment by hamachi25** [comment]
ご報告ありがとうございます。

使用している環境、ブラウザ、ブラウザバージョンを教えていただいてもよろしいでしょうか？
ちなみに、firefoxを使用している場合はHTTPS-Only モードを有効にする必要があります。

**Comment by Shirotan18** [comment]
無知なため、色々とお騒がせしてしまい申し訳ありません。
現在、スクリプトを再インストールしたところ、無事に使用できるようになりました。
念のため、質問事項についてお答えさせていただきます。

使用ブラウザ:Vivaldi
ブラウザバージョン:7.0.3495.18 (Stable channel) (64-bit) 
使用ブラウザ:Floorp Browser
ブラウザバージョン:11.20.0

また、Firefoxについての設定は知りませんでした。。
ありがとうございますm(_ _)m
